/* auth */
export enum Auth {
  SIGN_IN_REQUEST = 'SIGN_IN_REQUEST',
  SIGN_IN_SUCCEED = 'SIGN_IN_SUCCEED',
  SIGN_IN_FAILED = 'SIGN_IN_FAILED',
  SIGN_UP_REQUEST = 'SIGN_UP_REQUEST',
  SIGN_UP_FAILED = 'SIGN_UP_FAILED',
  LOGOUT = 'LOGOUT',
  REMOVE_AUTH_ERROR_MESSAGE = 'REMOVE_AUTH_ERROR_MESSAGE',
  CONFIRM_USER_REQUEST = 'CONFIRM_USER_REQUEST',
  CHANGE_PASSWORD_REQUEST = 'CHANGE_PASSWORD_REQUEST',
  CHANGE_PASSWORD_SUCCEED = 'CHANGE_PASSWORD_SUCCEED',
}

/* user */
export enum User {
  ADD_USER_TO_CHAT = 'ADD_USER_TO_CHAT',
  GET_SELECTED_CHAT = 'GET_SELECTED_CHAT',
  EDIT_CURRENT_USER_REQUEST = 'EDIT_CURRENT_USER_REQUEST',
  EDIT_CURRENT_USER_SUCCEED = 'EDIT_CURRENT_USER_SUCCEED',
}

/* message */
export enum Message {
  MESSAGES_REQUESTED = 'MESSAGES_REQUESTED',
  MESSAGES_SUCCEEDED = 'MESSAGES_SUCCEEDED',
  MESSAGES_FAILED = 'MESSAGES_FAILED',
  SEND_MESSAGE = 'SEND_MESSAGE',
  SEND_MESSAGE_FAILED = 'SEND_MESSAGE_FAILED',
  DELETE_MESSAGE = 'DELETE_MESSAGE',
  DELETE_MESSAGE_FAILED = 'DELETE_MESSAGE_FAILED',
  EDIT_MESSAGE = 'EDIT_MESSAGE',
}

/* chat */
export enum Chat {
  CREATE_CHAT = 'CREATE_CHAT',
  ADD_NEW_CHAT = 'ADD_NEW_CHAT',
  DELETE_CHAT = 'DELETE_CHAT',
  DELETE_OLD_CHAT = 'DELETE_OLD_CHAT',
  GET_ACTIVE_CHAT = 'GET_ACTIVE_CHAT',
  CLEAR_CHAT = 'CLEAR_CHAT',
  DELETE_USER_FROM_CHAT = 'DELETE_USER_FROM_CHAT',
  GET_CHAT_PARTICIPANTS = 'GET_CHAT_PARTICIPANTS',
  GET_CHAT_PARTICIPANTS_LOADED = 'GET_CHAT_PARTICIPANTS_LOADED',
  DELETE_UNWANTED_USER = 'DELETE_UNWANTED_USER',
  EDIT_CHAT_NAME = 'EDIT_CHAT_NAME',
  ADD_NEW_CHAT_NAME = 'ADD_NEW_CHAT_NAME',
}

/* oldUI */
export enum UI {
  IS_SHOW_USER_SETTINGS = 'IS_SHOW_USER_SETTINGS',
  IS_SHOW_CHAT_SETTINGS = 'IS_SHOW_CHAT_SETTINGS',
  IS_SHOW_LOGOUT = 'IS_SHOW_LOGOUT',
  IS_SHOW_CREATE_CHAT = 'IS_SHOW_CREATE_CHAT',
}
