/* user */
export const USER_FETCH_REQUESTED = 'USER_FETCH_REQUESTED';
export const USER_FETCH_SUCCEEDED = 'USER_FETCH_SUCCEEDED';
export const USER_FETCH_FAILED = 'USER_FETCH_FAILED';

export const USER_CREATE_REQUESTED = 'USER_CREATE_REQUESTED';

export const USER_LOGOUT = 'USER_LOGOUT';
export const REMOVE_AUTH_ERROR_MESSAGE = 'REMOVE_AUTH_ERROR_MESSAGE';

/* chat */

export const MESSAGES_REQUESTED = 'MESSAGES_REQUESTED';
export const MESSAGES_SUCCEEDED = 'MESSAGES_SUCCEEDED';
export const MESSAGES_FAILED = 'MESSAGES_FAILED';

export const SEND_MESSAGE = 'SEND_MESSAGE';
export const SEND_MESSAGE_FAILED = 'SEND_MESSAGE_FAILED';

export const DELETE_MESSAGE = 'DELETE_MESSAGE';
export const DELETE_MESSAGE_FAILED = 'DELETE_MESSAGE_FAILED';
export const EDIT_MESSAGE = 'EDIT_MESSAGE';

export const GET_ACTIVE_CHAT = 'GET_ACTIVE_CHAT';

export const CLEAR_CHAT = 'CLEAR_CHAT';
