/* user */
export const USER_FETCH_REQUESTED = 'USER_FETCH_REQUESTED';
export const USER_FETCH_SUCCEEDED = 'USER_FETCH_SUCCEEDED';
export const USER_FETCH_FAILED = 'USER_FETCH_FAILED';
export const USER_LOGOUT = 'USER_LOGOUT';
export const REMOVE_AUTH_ERROR_MESSAGE = 'REMOVE_AUTH_ERROR_MESSAGE';

/* chat */

export const GET_MESSAGES = 'GET_MESSAGES';
export const GET_ACTIVE_CHAT = 'GET_ACTIVE_CHAT';
